export const FETCH_DATA = "FETCH_DATA";
export const DATA_FETCHED = "DATA_FETCHED";

export const GET_ADDRESS_INFO = "GET_ADDRESS_INFO";
export const GET_ALL_ADDRESSES = "GET_ALL_ADDRESSES";
export const RESET_ADDRESS_STATE = "RESET_ADDRESS_STATE";
